### ISSUE TITLE
Content is lost when deserializing offer

### ISSUE THREAD

**Issue by lwillems** [coffeedesk/allegro-api-client-php#18]
Hi

First : thanks for your work, very useful to deal with Allegro.

I have encountered a bug when working with offer where description is defined.
Calling getOfferUsingGET on UsersOfferInformationApi class.

On raw API reply description is ok
```json
  "description": {
    "sections": [
      {
        "items": [
          {
            "type": "TEXT",
            "content": "<h1>A description</h1>"
          }
        ]
      }
    ]
  },
```

But when deseriazing items model is hardcoded to parent ($openApiTypes) which does not handle content (only type) so content is lost

```php
//vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSection.php
    protected static $openAPITypes = [
        'items' => '\AllegroApi\Model\DescriptionSectionItem[]'
    ];
```

Instead child model shoud be used 

- vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSectionItemText.php
- vendor/coffeedesk/allegro-api-client-php/src/Model/DescriptionSectionItemImage.php

Regards

**Comment by Arkowsky** [comment]
Hi,
we use some openapi-generator to generate this code and sometimes this has some issues. Feel free just make some pull request to fix that issue :).

**Comment by lwillems** [comment]
> Hi,
> we use some openapi-generator to generate this code and sometimes this has some issues. Feel free just make some pull request to fix that issue :).

Done :)
